### ISSUE TITLE
Differences between img_list and image_list

### ISSUE THREAD

**Issue by irosenb** [BonMatts/wikiwhat#9]
I'm confused as to what the differences are between img_list and image_list. It's not clear by the names. Could you explain? I'm working on changing some of the names.

**Comment by irosenb** [comment]
I seem to kinda get it. Img_list is only as a parameter to pass in when making a new object…

Sorry, I forgot to congratulate you guys on making your first gem! It's quite impressive for your first Ruby Gem, and one of your first Ruby programs.

**Comment by cglinka** [comment]
Yes, img_list is just the initialization parameter. They have to have separate names because we memoized our internal functions. Technically, image_list should be media_list, but we haven't fixed that yet. :)

Thanks! We had a lot of fun building it.

**Comment by irosenb** [comment]
Image_list would make more sense if it was called images. Unless you're retrieving other content, images is a really clean representation of what you're getting from the page.

**Comment by cglinka** [comment]
That method currently pulls back all the media on the page, not just images.
